### ISSUE TITLE
Something wrong with itertating (maybe hashtable bug?)

### ISSUE THREAD

**Issue by yav** [GaloisInc/galua#16]
To see the problem, need Trevor's game (at 9e7d3975b82c29df...) .

Modify the function returned by Set:iter()  to print the overall number of iterations---with the reference Lua implementation I get a few hundred calls (235).  With Galua it seems to never finish, and goes well beyond this number.

**Comment by glguy** [comment]
https://github.com/elliottt/love-experiments/commit/9e7d3975b82c29df31948772a673b85b0e14613a

**Comment by glguy** [comment]
Fixed in 3a398d4e38fc94daee07bb20e78728a7133cfcfe
